import { Component } from '@angular/core';


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'hello my-app';

  constructor(){
    console.log('this statement was generated by the constructor ');


  }


}
